### ISSUE TITLE
some advise about rulerz

### ISSUE THREAD

**Issue by zsytssk** [forgecrafted/rulerz#13]
ruler provide easer way find cursor when you tired
so ruler style must be simple clear no ugly
I think ruler color should like cursor color than text color, and add opacity: 0.5
ruler line should use dashed not solid just like editpus
solid line is more annoying, maybe that is not best but better than now 
should have shortcut easy hide or show ruler, <ctrl> is the best

**Comment by cmtonkinson** [comment]
Let's roll this into #15 - having a discussion about @n3dst4 about this same thing.
