### ISSUE TITLE
Enhancement: Disable rulerz for first character in line

### ISSUE THREAD

**Issue by tairun** [forgecrafted/rulerz#16]
When the cursor sits on the first character of the line, the ruler clashes with the right border of the gutter, which looks awkward. I don't know how to style this with css and think this should be easier to implement functionally.

This :-(
![image](https://cloud.githubusercontent.com/assets/4248906/10667490/ead81a72-78d7-11e5-95c5-d26de3725aab.png)

as oposed to this:
![image](https://cloud.githubusercontent.com/assets/4248906/10667529/1c741e82-78d8-11e5-9cb7-6e4eaf532d6d.png)

**Comment by cmtonkinson** [comment]
Which Atom/Syntax Themes are you using? I don't see any combination which creates a visible right border on the gutter.

![no-gutter-border](https://cloud.githubusercontent.com/assets/281467/10667865/a69f9072-78a7-11e5-813e-171281739fe6.png)

**Comment by tairun** [comment]
I'm using One Dark UI (Compact) and Base16 Tomorrow for Syntax. I have linter installed which adds a second gutter by default. But disabling the package didn't do any good.

**Comment by n3dst4** [comment]
So I've just tried, and it's Base 16 Tomorrow that adds the right border on the gutters.

Could I suggest this snippet of custom CSS which you could put in your user stylesheet to remove that border?

``` less
.gutter {
  border-right-style: none;
}
```

![2015-10-25 16_29_28-styles less - c__git_ssln-scaffold - atom](https://cloud.githubusercontent.com/assets/280206/10716580/9b90d746-7b35-11e5-9623-9369a0475d0f.png)

**Comment by cmtonkinson** [comment]
We could disable the gutter border in the package styles, but that seems a bit scorched-earth.

Another approach could be to disable the gutter specifically for Base16 Tomorrow. I'm not sure whether this is per an Atom specification or just a convention (I've never played with Atom Themes before), but each Theme (Atom and Syntax alike) seem to be adding a class to the outtermost `<atom-workspace>`. Case and point, I see a `theme-base16-tomorrow-dark-theme` class which would be trivially targetable.

In any event, I'm not sure it's wise to add actual logic specific to Theme variations.

Thoughts?

---

@tairun Until we get this sorted out, @n3dst4's workaround is your best bet.

**Comment by tairun** [comment]
> In any event, I'm not sure it's wise to add actual logic specific to Theme variations.

I agree, maintaining a "database" with "bad" themes would be tedious.

@n3dst4 solution is fine with me for the moment. By the way, for my installation (windows @1.0.19) the correct css selector is `atom-text-editor::shadow .gutter` (Don't know if that's standard for you guys) :+1: 

I enabled the "highlight error lines in gutter" option from the linter package again and it does some weird stuff.
![image](https://cloud.githubusercontent.com/assets/4248906/10740812/955b1dec-7c24-11e5-91fe-66979b14eeb2.png)
(highlight on right, right-border none)

![image](https://cloud.githubusercontent.com/assets/4248906/10740922/46e711f6-7c25-11e5-8b08-a8641f12e7cf.png)
(highlight on left, right-border none)

![image](https://cloud.githubusercontent.com/assets/4248906/10740945/6cb395da-7c25-11e5-8f17-10f4487ab586.png)
(highlight on left, left-border none)

What I'm trying to say is, there seems to be no way to style the middle border.

**Comment by tairun** [comment]
> What I'm trying to say is, there seems to be no way to style the middle border.

Ok, did some quick testing and got it "right". Really specific selector from dev tools (I know this might be different for everyone. Depends on themes and packages installed):

``` css
atom-text-editor::shadow div > div > div.gutter-container > div:nth-child(2) {
   border-left-style: none;
}
```

![image](https://cloud.githubusercontent.com/assets/4248906/10741398/e63ba044-7c27-11e5-832d-bb3ab275a25c.png)

**Comment by tairun** [comment]
By the way I realize this is not this packages fault. But there might be a solution from the core devs:  

> - Base16 Tomorrow themes have now a seamless gutter and other minor fixes.

News on update page: https://atom.io/releases

**Comment by cmtonkinson** [comment]
Since you've got a workaround (and I read the 1.1 beta release notes the same way you do - that they're removing the extra gutter border anyway) is it safe to close?

**Comment by tairun** [comment]
I think yes, go ahead.
