### ISSUE TITLE
Deprecated selector in `rulerz/styles/cursor-ruler.less`

### ISSUE THREAD

**Issue by carolfalardeau** [forgecrafted/rulerz#21]
In `rulerz/styles/cursor-ruler.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor.is-focused::shadow ruler-view.rulerz` => `atom-text-editor.is-focused.editor ruler-view.rulerz`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by sergeysova** [comment]
@BattleBrisket @cmtonkinson

**Comment by BattleBrisket** [comment]
@LestaD @cmtonkinson is the driver on this one, and has been busy with his wife welcoming their second child to the world earlier this week.

Fortunately, this is a volunteer effort, and open source contributions look great on a resume - https://github.com/forgecrafted/rulerz#contributing

**Comment by danielbayley** [comment]
PR #22 already fixes this… it just needs merging!
