### ISSUE TITLE
Add rulerz to vsCode?

### ISSUE THREAD

**Issue by sergeysova** [forgecrafted/rulerz#23]

**Comment by cmtonkinson** [comment]
I don't use or know much about vsCode, but I'd be happy to help!

Do you know if this will require refactoring, or is it simply a matter of registering the plugin with another service?

**Comment by cmtonkinson** [comment]
Thanks for using rulerz, and caring enough to submit a bug report! We're no longer actively using Atom day-to-day, and so haven't devoted a great deal of time to the package. If you're interested in picking up maintainership, please let me know.

**Comment by chmac** [comment]
@sergeysova Hope you found a solution for vscode. Will close this issue now as it's pretty old and this project is not (very) actively maintained.
