### ISSUE TITLE
Ruler not appearing when opening new tab since 1.19.0 release

### ISSUE THREAD

**Issue by josh08h** [forgecrafted/rulerz#26]
The vertical ruler only appears if I have a tab open and disable/enable the Rulerz plugin.

Seemingly since 1.19.0 upgrade.

**Comment by cmtonkinson** [comment]
Thanks for using rulerz, and caring enough to submit a bug report! We're no longer actively using Atom day-to-day, and so haven't devoted a great deal of time to the package. If you're interested in picking up maintainership, please let me know.

**Comment by chmac** [comment]
@josh08h Not sure if you're still using this package or not, but hopefully the issue has been fixed in the latest 0.5.0 release.
