### ISSUE TITLE
Open to taking over maintenance

### ISSUE THREAD

**Issue by chmac** [forgecrafted/rulerz#27]
I've been hammered by #25 for a while. Put some time into it today and have found a hacky workaround. Will post a PR shortly. I'm also open to taking over (very limited) maintenance of this package if you like.

**Comment by cmtonkinson** [comment]
@chmac are you still interested in maintainership? I'm simply not able to give the package the attention it deserves at this point.

**Comment by chmac** [comment]
@cmtonkinson I'm still using the plugin after my dirty, dirty, dirty hack of a workaround. I'd be happy to merge that fix and see if I can answer a question from time to time. Can't promise a ton of attention / effort.

If you wanted to add me as a contributor here on this repo, that might be an easy step. Then we don't need to change anything, keep it in your name, etc. I can merge the fix and subscribe to issue notifications. If I do nothing at all, then we're in the same position as now! :-)

What do you think?

If I merge here does that automatically deploy an update to the atom.io plugin repository, or would I also need access there and have to do something manually to push it?

**Comment by cmtonkinson** [comment]
Unsure whether Atom.io permissions directly mirror those of GitHub, but if you're not able to `apm publish patch` that MR, let me know.

**Comment by chmac** [comment]
@cmtonkinson Awesome, looks like I published version `0.5.0`. I now realise that `minor` meant it pushed a minor release as opposed to a patch release. Probably makes sense. Will close this issue now.
