### ISSUE TITLE
Leading Tabs Throw Off Ruler

### ISSUE THREAD

**Issue by hatzopoulos** [forgecrafted/rulerz#3]
Nice package but it seems to not play nicely with leading tabs.

**Multi Cursors** (orange block is my cursor) 
![image](https://cloud.githubusercontent.com/assets/1771931/6032848/33a9e10a-abdc-11e4-9fb4-bc1a5463b218.png)

**Single cursor example**
![image](https://cloud.githubusercontent.com/assets/1771931/6032842/1a8a22e8-abdc-11e4-9296-8588b3972f49.png)

**Comment by cmtonkinson** [comment]
Thanks for the report! We're a `softTabs: true` bunch so this definitely wasn't on our radar. Also likely related to #2 - probably mixed up a bufferPosition with a screenPosition call somewhere.

**Comment by cmtonkinson** [comment]
Fixed in 447c46e
