### ISSUE TITLE
Kudos !

### ISSUE THREAD

**Issue by icylace** [forgecrafted/rulerz#4]
I'm the creator of CursorRuler and I'm not submitting an issue but a thank you instead!  I've recently been looking into Atom a little more seriously and stumbled upon rulerz a few moments ago.  I installed it and enjoy using it.

I have plans for the future of CursorRuler which included the possibility of porting it to Atom but I don't know if and when I'll be able to do it.

That being said I'm very glad rulerz exists and thank you for being inspired by my plugin.  :)

**Comment by cmtonkinson** [comment]
Thanks very much @icylace! _We_ should be thanking _you_ for the inspiration :)

**Comment by icylace** [comment]
:)
